app/db/models/pizza.py
from sqlalchemy.orm import Mapped,mapped_column
from sqlalchemy import String

from app.db.base import Base


class Pizza(Base):
    __tablename__ = "pizzas"

    id: Mapped[int] = mapped_column(primary_key=True)
    price: Mapped[float] = mapped_column()
    name: Mapped[str] = mapped_column(String())

app/__init__.py
from flask import Flask

from app.db.base import create_db
from app.routes import pizza_route
from app.data.password import ADMIN_PASS


app = Flask(__name__)
app.secret_key = ADMIN_PASS
app.register_blueprint(pizza_route)

def main():
    create_db()
    app.run(debug=True)

app/routes/__init__.py
from app.routes.pizza import pizza_route

app/routes/pizza.py
from flask import Blueprint,render_template,request,redirect,flash,url_for
from app.db.__init import Session,Pizza
from app.data.password import ADMIN_PASS


pizza_route = Blueprint("pizzas", __name__)

@pizza_route.get("/pizzas/")
@pizza_route.post("/pizzas/")
def add_pizza():
     with Session() as session:
        if request.method == "POST":
            name = request.form.get("name")
            price = request.form.get("price")
            pizza = Pizza(name=name,price=price)

            if request.form.get("password") == ADMIN_PASS:
                session.add(pizza)
                session.commit()
                flash("Піццу успішно додано")
                return redirect(url_for("pizzas.index"))
            else:
                flash("Нeвийшло додати піцу")

        return render_template("add_pizza.html")


@pizza_route.get("/pizza/del/<int:id>/")
def del_pizza(id):
    with Session() as session:
        pizza = session.query(Pizza).where(Pizza.id == id).first()
        session.delete(pizza)
        session.commit()
        return redirect(url_for("pizzas.index"))

@pizza_route.get("/")
def index():
     with Session() as session:
        pizzas = session.query(Pizza).all()
        return render_template("index.html", pizzas=pizzas)



@pizza_route.get("/pizza/edit/<int:id>")
@pizza_route.post("/pizza/edit/<int:id>")
def edit_pizza(id):
    with Session() as session:
        pizza = session.query(Pizza).where(Pizza.id == id).first()
        if request.method == "POST":
            name = request.form.get("name")
            price = request.form.get("price")

            pizza.name = name
            pizza.price = price
            session.commit()
            return redirect(url_for("pizzas.index"))

        return render_template("edit_pizza.html", pizza=pizza)

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title %} FlaskBlog {% endblock title %}</title>
</head>
<body class="p-5 bg-primary-subtle">
    {% include "_navigation.html" %}
    {% block content %}
    {% endblock content %}
    <div class="container text-center">
        <div class="row">
            <div class="col">
                {% block left_content %}
                {% endblock left_content %}
            </div>
            <div class="col">
                {% block center_content %}
                {% endblock center_content %}
            </div>
            <div class="col">
                {% block right_content %}
                {% endblock right_content %}
            </div>
        </div>
    </div>
</body>
</html>

app/templates/_navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('pizzas.index') }}">Головна сторінка</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('pizzas.add_pizza') }}">Додати піццу</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/templates/add_pizza.html
{% extends "_base.html" %}

{% block center_content %}
<form action="{{ url_for('pizzas.add_pizza') }}" method="post">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Назва піцци</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="name">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">ціна піцци</label>
    <input type="number" class="form-control" id="exampleInputEmail1" name="price">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Додати</button>
  <h3>{{ msg }}</h3>
</form>

{% if block %}
    <img src="https://http.cat/401">
{% endif %}
{% endblock center_content %}

app/templates/edit_pizza.html
{% extends "_base.html" %}

{% block center_content %}
<form action="{{ url_for('pizzas.add_pizza') }}" method="pizza">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Назва піцци</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="name" value="{{pizza.name}}">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">ціна піцци</label>
    <input type="number" class="form-control" id="exampleInputEmail1" name="price" value="{{pizza.price}}">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Додати</button>
  <h3>{{ msg }}</h3>
</form>

{% if block %}
    <img src="https://http.cat/401">
{% endif %}
{% endblock center_content %}

app/templates/index.html
{% extends "_base.html" %}

{% block content %}
{% block title %}
    PIZZERIA DE MAINTO
{% endblock title %}
{% endblock content %}

{% block center_content %}
    {% for pizza in pizzas %}
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">Назва піцци</h5>
            <p class="card-text"><em>Ціна піцци: </em>{{ pizza.price }}</p>
            <a href="{{url_for('pizzas.edit_pizza', id=pizza.id)}}">редагувати</a>
            <a href="{{url_for('pizzas.del_pizza', id=pizza.id)}}">видалити</a>
        </div>
        </div>
    {% endfor %}
{% endblock center_content %}

app/templates/pizza.html
{% extends "_base.html" %}

{% block center_content %}
<form action="{{ url_for('pizzas.add_pizza') }}" method="pizza">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Назва піцци</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="name">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Додати</button>
  <h3>{{ msg }}</h3>
</form>

{% if block %}
    <img src="https://http.cat/401">
{% endif %}
{% endblock center_content %}